env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  binary: crypto
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
snapcrafts:
  -
    id: crypto
    builds:
    - crypto
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name: crypto
    publish: true
    summary: Cryptocurrency tool for the command-line.
    description: Crypto is a simple, robust command-line application that displays the price of popular cryptocurrencies.
    grade: stable
    confinement: strict
    license: Apache-2.0
    base: core20
    apps:
      crypto:
        plugs: ["network"]
brews:
  - tap:
      owner: jasonbirchall
      name: homebrew-tap
    homepage: https://github.com/jasonBirchall/crypto
    description: Cryptocurrency tracker for the command line.
    license: Apache-2.0
    dependencies:
    - name: go
