name: crypto
base: core20 # the base snap is the execution environment for this snap
version: '0.1.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: Cryptocurrency tool for the command-line.
description: |
  Crypto is a simple, robust command-line application that displays the price of popular cryptocurrencies.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # restricts permissions so only interfaces allowed

parts:
  crypto:
    plugin: go
    source: .
    build-packages:
      - git
      - gcc

apps:
  crypto:
    command: bin/crypto-tracker
    plugs:
      - network
