name: Renew documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@master

      - name: Run makefile
        run: |
          make update-pkg-cache
