name: Renew documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@1.0.1
